version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - .:/usr/src/app
      #- /usr/src/app/node_modules
      #- /usr/src/app/.next
    env_file:
      - .env
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"
